name: Container Images
on:
  push:
    branches:
      - master
      - main
    tags:
      - v*
  pull_request:

jobs:
  container_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/metadata-action@v3
        id: meta-centos
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch,prefix=centos-
            type=ref,event=pr,prefix=centos-
            type=semver,pattern={{version}},prefix=centos-
            type=semver,pattern={{major}}.{{minor}},prefix=centos-
            type=semver,pattern={{major}},prefix=centos-
            type=sha,prefix=centos-
          labels: |
            org.opencontainers.image.licenses=AGPL-3.0
          flavor: |
            latest=false
            prefix=centos-
      - uses: docker/metadata-action@v3
        id: meta-debian
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch,prefix=debian-
            type=ref,event=pr,prefix=debian-
            type=semver,pattern={{version}},prefix=debian-
            type=semver,pattern={{major}}.{{minor}},prefix=debian-
            type=semver,pattern={{major}},prefix=debian-
            type=sha,prefix=debian-
          labels: |
            org.opencontainers.image.licenses=AGPL-3.0
          flavor: |
            latest=true
            prefix=debian-
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        id: build-push-centos
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-centos.outputs.tags }}
          labels: ${{ steps.meta-centos.outputs.labels }}
          platforms: linux/amd64
          file: Dockerfile.centos
      - uses: docker/build-push-action@v2
        id: build-push-debian
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-debian.outputs.tags }}
          labels: ${{ steps.meta-debian.outputs.labels }}
          platforms: linux/amd64
          file: Dockerfile.debian
